data:
  type: cell
  source: mouse
  target: human
  condition: species_label
  path: /home/dor3/cell2sentence/cross_species/Syed_CellOT_Code/datasets/harmony_common_pancreas_20241025.h5ad
  dimension_reduction:
    name: harmony

dataloader:
  batch_size: 256
  shuffle: true

datasplit:
  groupby: species_label 
  name: train_test_eval
  test_size: 500
  eval_size: 500
  random_state: 0
