data:
  type: cell
  source: human
  target: mouse
  condition: species_label
  path: /home/sr2464/scratch/C2S_Files/CellOT_files/pancreas_data/harmony_common_pancreas.h5ad
  dimension_reduction:
    name: pca

dataloader:
  batch_size: 256
  shuffle: true

datasplit:
  groupby: species_label 
  name: train_test_eval
  test_size: 500
  eval_size: 500
  random_state: 0
